version: '3.8'
services:
  webserver:
    container_name: "${PROJECT_NAME}-${PHPVERSION}"
    build:
      context: ./bin/${PHPVERSION}
    volumes:
      - ./:/${PROJECT_NAME}
      - ./html:/var/www/html:rw
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./logs/apache2:/var/log/apache2
      - ./cron:/etc/cron.d/cron
      - ./logs/cron:/var/logs/cron
    ports:
      - ${WEBSERVER_PORT}:80
    links:
      - database
    # environment:
    #   TZ: ${TIMEZONE}
  database:
    container_name: "${PROJECT_NAME}-${DATABASE}"
    build: 
      context: ./bin/${DATABASE}
    ports:
      - ${MYSQL_TCP_PORT}:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: ${MYSQL_TCP_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}